[workspace]
authors = ["Ollie Tooth <oliver.tooth@noc.ac.uk>"]
preview = ["pixi-build"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64"]

[package]
name = "nemo_cookbook"
version = "9999.0.0"

[package.build]
backend = { name = "pixi-build-python", version = ">=0.4.4" }

[package.host-dependencies]
setuptools = "*"
setuptools_scm = "*"

[package.run-dependencies]
python = "*"
aiohttp = "*"
dask = "*"
flox = "*"
fsspec = "*"
icechunk = "*"
matplotlib = "*"
numbagg = "*"
numba = "0.62*"
numpy = "2.3*"   # numba 0.62 added support for numpy 2.3
netCDF4 = "*"
pooch = "*"
requests = "*"
scikit-learn = "*"
scikit-image = "*"
xarray = "*"
xoak = "*"
zarr = "*"
git = "*"  # needed for dynamic versioning

[dependencies]
nemo_cookbook = { path = "." }
python = "3.13.*"

[feature.test.pypi-dependencies]
pytest = "*"
pytest-mock = "*"

[feature.test.tasks]
test = { cmd = "pytest --maxfail=1 --disable-warnings --tb=short", description = "Run NEMO Cookbook unit tests using pytest." }

[feature.docs.pypi-dependencies]
mkdocs-material = "*"
mkdocs-glightbox = "*"
mkdocs-jupyter = ">=0.26.1"
mkdocstrings = "*"
mkdocstrings-python = "*"

[feature.docs.tasks]
docs = { cmd = "cd docs/; mkdocs serve", description = "Run the MkDocs built-in development server to build docs locally." }

[feature.dev.dependencies]
cartopy = ">=0.25.0,<0.26"
ipykernel = ">=7.2.0,<8"
nc-time-axis = "*"
notebook = "*"
pyarrow = "*"
gsw = "*"
xesmf = ">=0.8.7,<0.10"

[environments]
default = { solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
docs = { features = ["docs"], solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
