site_name: NEMO Cookbook Documentation
site_url: https://noc-msm.github.io/nemo_cookbook/

repo_url: https://github.com/NOC-MSM/nemo_cookbook
repo_name: nemo_cookbook
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  logo: assets/icons/noc_logo.png
  favicon: assets/icons/favicon.ico
  icon:
    edit: material/pencil 
    view: material/eye
    repo: fontawesome/brands/git-alt
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.action.edit
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - toc.integrate
    - navigation.tabs
    - navigation.path
    - navigation.footer
    - search.suggest

  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: light blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - md_in_html
  - pymdownx.blocks.caption

nav:
  - Getting started: index.md
  - User Guide:
    - NEMODataTree: nemodatatree.md
    - Example NEMODataTrees: examples.md
  - Recipes:
    - Meridional Overturning - Depth Space: recipe_moc_z.ipynb
    - Meridional Overturning - Tracer Space: recipe_moc_tracer.ipynb
    - Regional Masked Statistics: recipe_masked_stats.ipynb
    - Volume Census in T-S Space: recipe_volume_census.ipynb
    - Surface-Forced Water Mass Transformation: recipe_sfwmt_sigma0.ipynb
    - Extracting Hydrographic Sections: recipe_extract_osnap.ipynb
    - Vertical Coordinate Transformation: recipe_transform_vertical_coords.ipynb
  - API: reference.md
  - Contributing: contributing.md

plugins:
  - search
  - glightbox
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: "table"
            filters: "public"
            separate_signature: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_heading: true
            summary: true
            allow_inspection: false
          paths: [../nemo_cookbook]
  - mkdocs-jupyter:
      include_source: True

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/NOC-MSM/nemo_cookbook
      name: GitHub

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js