name:  nemo_cookbook_Docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocs-glightbox mkdocs-jupyter mkdocstrings mkdocstrings-python
          pip install git+https://github.com/NOC-MSM/nemo_cookbook.git
      - working-directory: ./docs
        run: mkdocs gh-deploy --force